### ISSUE TITLE
"Calculate Total" throws an error of "trying to access array offset on value of type null"

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-reports-commerce#8]
```
yii\base\ErrorException: Trying to access array offset on value of type null in /srv/app/website/htdocs/vendor/barrelstrength/sprout-reports-commerce/src/integrations/sproutreports/datasources/CommerceOrderHistoryDataSource.php:225
Stack trace:
#0 /srv/app/website/htdocs/vendor/craftcms/cms/src/web/ErrorHandler.php(74): yii\base\ErrorHandler->handleError(8, 'Trying to acces...', '/srv/app/website...', 225)
#1 /srv/app/website/htdocs/vendor/barrelstrength/sprout-reports-commerce/src/integrations/sproutreports/datasources/CommerceOrderHistoryDataSource.php(225): craft\web\ErrorHandler->handleError(8, 'Trying to acces...', '/srv/app/website...', 225, Array)
#2 /srv/app/website/htdocs/vendor/barrelstrength/sprout-reports-commerce/src/integrations/sproutreports/datasources/CommerceOrderHistoryDataSource.php(133): barrelstrength\sproutreportscommerce\integrations\sproutreports\datasources\CommerceOrderHistoryDataSource->getTotalAdjustmentByType('Tax')
#3 /srv/app/website/htdocs/vendor/barrelstrength/sprout-reports-commerce/src/integrations/sproutreports/datasources/CommerceOrderHistoryDataSource.php(59): barrelstrength\sproutreportscommerce\integrations\sproutreports\datasources\CommerceOrderHistoryDataSource->getReportWithCalculateTotals()
#4 /srv/app/website/htdocs/vendor/barrelstrength/sprout-base-reports/src/controllers/ReportsController.php(160): barrelstrength\sproutreportscommerce\integrations\sproutreports\datasources\CommerceOrderHistoryDataSource->getResults(Object(barrelstrength\sproutbasereports\elements\Report))
```

**Comment by john-henry** [comment]
Running into this now too. Is this still in active dev @BenParizek ?

**Comment by BenParizek** [comment]
@john-henry I just pushed up a fix with release v1.0.5.

Still active and you'll be seeing more releases again soon!

**Comment by john-henry** [comment]
That's great Ben. I upgraded to the latest but now I get No Results if Calculate Total is turned off where I did previously and when I turn on Calculate Total it seems off and is a negative number the Product revenue column

**Comment by john-henry** [comment]
@BenParizek feel free to reach out on Discord and I can share a screen with you

**Comment by BenParizek** [comment]
@john-henry Looks like I flip/flopped another small change with deleted order logic so the query was only returning deleted orders. 

I've just pushed v1.0.6 that should resolve this.
